### ISSUE TITLE
Installing this starter

### ISSUE THREAD

**Issue by ghost** [ChristopherBiscardi/gatsby-starter-theme#4]
When installing this theme I get an endless stream of.....
![gatsby-starter-theme](https://user-images.githubusercontent.com/1179369/54449242-ddec3280-470a-11e9-876e-f144afec6156.JPG)

**Comment by ChristopherBiscardi** [comment]
This seems like it's related to [your git config](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_code_core_autocrlf_code) because you are on Windows and this repo is developed mainly on unix based systems.
